---

- name: create /etc/prometheus
  file:
    path: /etc/prometheus
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create the prometheus user
  group:
    name: prometheus
    state: present

- name: create the prometheus user
  user:
    name: prometheus
    group: prometheus
    shell: /bin/false
    create_home: false
    state: present

- name: create /var/lib/prometheus
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755

- name: fetch latest prometheus version
  shell: curl -s -o /dev/null -I -w "%{redirect_url}\n" https://github.com/prometheus/prometheus/releases/latest | grep -oP "[0-9]+(\.[0-9]+)+$"
  args:
    executable: /bin/bash
  register: prometheus_version

- name: download prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version.stdout }}/prometheus-{{ prometheus_version.stdout }}.linux-amd64.tar.gz
    owner: root
    group: root
    dest: /root/prometheus-{{ prometheus_version.stdout }}.linux-amd64.tar.gz
    mode: 0755

- name: Unarchive prometheus
  unarchive:
    src: /root/prometheus-{{ prometheus_version.stdout }}.linux-amd64.tar.gz
    dest: /root
    remote_src: yes

- name: copy prometheus to /usr/local/bin/prometheus
  copy:
    src: /root/prometheus-{{ prometheus_version.stdout }}.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: yes

- name: copy promtool to /usr/local/bin/promtool
  copy:
    src: /root/prometheus-{{ prometheus_version.stdout }}.linux-amd64/promtool
    dest: /usr/local/bin/promtool
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: yes

- name: copy console_libraries to /etc/prometheus/console_libraries
  copy:
    src: /root/prometheus-{{ prometheus_version.stdout }}.linux-amd64/console_libraries
    dest: /etc/prometheus/console_libraries
    owner: prometheus
    group: prometheus
    mode: 0644
    remote_src: yes

- name: copy consoles to /etc/prometheus/consoles
  copy:
    src: /root/prometheus-{{ prometheus_version.stdout }}.linux-amd64/consoles
    dest: /etc/prometheus/consoles
    owner: prometheus
    group: prometheus
    mode: 0644
    remote_src: yes

- name: add prometheus.yml
  template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0644

- name: add prometheus.rules.yml
  template:
    src: prometheus.rules.yml
    dest: /etc/prometheus/prometheus.rules.yml
    owner: prometheus
    group: prometheus
    mode: 0644

- name: add prometheus systemd unit file
  template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    mode: 0644

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: enable prometheus
  systemd:
    name: prometheus
    enabled: yes

- name: start prometheus
  systemd:
    name: prometheus
    state: started

...
